export type TCounty = '基隆市' | '臺北市' | '新北市' | '桃園市' | '新竹市' | '新竹縣' | '苗栗縣' | '台中市' | '彰化縣' | '南投縣' | '雲林縣' | '嘉義市' | '嘉義縣' | '台南市' | '高雄市' | '屏東縣' | '台東縣' | '花蓮縣' | '宜蘭縣' | '澎湖縣' | '金門縣' | '連江縣';

const YEAR_LIST = [
  { title: '106', value: '106' },
  { title: '107', value: '107' },
  { title: '108', value: '108' },
  { title: '109', value: '109' },
  { title: '110', value: '110' },
  { title: '110', value: '111' },
];

export const COUNTY_LIST:Array<{ title:TCounty, value:string }> = [
  { title: '基隆市', value: '基隆市' },
  { title: '臺北市', value: '臺北市' },
  { title: '新北市', value: '新北市' },
  { title: '桃園市', value: '桃園市' },
  { title: '新竹市', value: '新竹市' },
  { title: '新竹縣', value: '新竹縣' },
  { title: '苗栗縣', value: '苗栗縣' },
  { title: '台中市', value: '台中市' },
  { title: '彰化縣', value: '彰化縣' },
  { title: '南投縣', value: '南投縣' },
  { title: '雲林縣', value: '雲林縣' },
  { title: '嘉義市', value: '嘉義市' },
  { title: '嘉義縣', value: '嘉義縣' },
  { title: '台南市', value: '台南市' },
  { title: '高雄市', value: '高雄市' },
  { title: '屏東縣', value: '屏東縣' },
  { title: '台東縣', value: '台東縣' },
  { title: '花蓮縣', value: '花蓮縣' },
  { title: '宜蘭縣', value: '宜蘭縣' },
  { title: '澎湖縣', value: '澎湖縣' },
  { title: '金門縣', value: '金門縣' },
  { title: '連江縣', value: '連江縣' },
];

export const TOWN_MAP:{ [key in TCounty]:Array<{ title:string, value:string }> } = {
  基隆市: [{ title: '仁愛區', value: '仁愛區' }, { title: '中正區', value: '中正區' }, { title: '信義區', value: '信義區' }, { title: '中山區', value: '中山區' }, { title: '安樂區', value: '安樂區' }, { title: '暖暖區', value: '暖暖區' }, { title: '七堵區', value: '七堵區' }],
  臺北市: [{ title: '中正區', value: '中正區' }, { title: '大同區', value: '大同區' }, { title: '中山區', value: '中山區' }, { title: '萬華區', value: '萬華區' }, { title: '信義區', value: '信義區' }, { title: '松山區', value: '松山區' }, { title: '大安區', value: '大安區' }, { title: '南港區', value: '南港區' }, { title: '北投區', value: '北投區' }, { title: '內湖區', value: '內湖區' }, { title: '士林區', value: '士林區' }, { title: '文山區', value: '文山區' }],
  新北市: [{ title: '板橋區', value: '板橋區' }, { title: '新莊區', value: '新莊區' }, { title: '泰山區', value: '泰山區' }, { title: '林口區', value: '林口區' }, { title: '淡水區', value: '淡水區' }, { title: '金山區', value: '金山區' }, { title: '八里區', value: '八里區' }, { title: '萬里區', value: '萬里區' }, { title: '石門區', value: '石門區' }, { title: '三芝區', value: '三芝區' }, { title: '瑞芳區', value: '瑞芳區' }, { title: '汐止區', value: '汐止區' }, { title: '平溪區', value: '平溪區' }, { title: '貢寮區', value: '貢寮區' }, { title: '雙溪區', value: '雙溪區' }, { title: '深坑區', value: '深坑區' }, { title: '石碇區', value: '石碇區' }, { title: '新店區', value: '新店區' }, { title: '坪林區', value: '坪林區' }, { title: '烏來區', value: '烏來區' }, { title: '中和區', value: '中和區' }, { title: '永和區', value: '永和區' }, { title: '土城區', value: '土城區' }, { title: '三峽區', value: '三峽區' }, { title: '樹林區', value: '樹林區' }, { title: '鶯歌區', value: '鶯歌區' }, { title: '三重區', value: '三重區' }, { title: '蘆洲區', value: '蘆洲區' }, { title: '五股區', value: '五股區' }],
  桃園市: [{ title: '桃園區', value: '桃園區' }, { title: '中壢區', value: '中壢區' }, { title: '平鎮區', value: '平鎮區' }, { title: '八德區', value: '八德區' }, { title: '楊梅區', value: '楊梅區' }, { title: '蘆竹區', value: '蘆竹區' }, { title: '龜山區', value: '龜山區' }, { title: '龍潭區', value: '龍潭區' }, { title: '大溪區', value: '大溪區' }, { title: '大園區', value: '大園區' }, { title: '觀音區', value: '觀音區' }, { title: '新屋區', value: '新屋區' }, { title: '復興區', value: '復興區' }],
  新竹市: [{ title: '東區', value: '東區' }, { title: '北區', value: '北區' }, { title: '香山區', value: '香山區' }],
  新竹縣: [{ title: '竹北市', value: '竹北市' }, { title: '竹東鎮', value: '竹東鎮' }, { title: '新埔鎮', value: '新埔鎮' }, { title: '關西鎮', value: '關西鎮' }, { title: '峨眉鄉', value: '峨眉鄉' }, { title: '寶山鄉', value: '寶山鄉' }, { title: '北埔鄉', value: '北埔鄉' }, { title: '橫山鄉', value: '橫山鄉' }, { title: '芎林鄉', value: '芎林鄉' }, { title: '湖口鄉', value: '湖口鄉' }, { title: '新豐鄉', value: '新豐鄉' }, { title: '尖石鄉', value: '尖石鄉' }, { title: '五峰鄉', value: '五峰鄉' }],
  苗栗縣: [{ title: '苗栗市', value: '苗栗市' }, { title: '通霄鎮', value: '通霄鎮' }, { title: '苑裡鎮', value: '苑裡鎮' }, { title: '竹南鎮', value: '竹南鎮' }, { title: '頭份鎮', value: '頭份鎮' }, { title: '後龍鎮', value: '後龍鎮' }, { title: '卓蘭鎮', value: '卓蘭鎮' }, { title: '西湖鄉', value: '西湖鄉' }, { title: '頭屋鄉', value: '頭屋鄉' }, { title: '公館鄉', value: '公館鄉' }, { title: '銅鑼鄉', value: '銅鑼鄉' }, { title: '三義鄉', value: '三義鄉' }, { title: '造橋鄉', value: '造橋鄉' }, { title: '三灣鄉', value: '三灣鄉' }, { title: '南庄鄉', value: '南庄鄉' }, { title: '大湖鄉', value: '大湖鄉' }, { title: '獅潭鄉', value: '獅潭鄉' }, { title: '泰安鄉', value: '泰安鄉' }],
  台中市: [{ title: '中區', value: '中區' }, { title: '東區', value: '東區' }, { title: '南區', value: '南區' }, { title: '西區', value: '西區' }, { title: '北區', value: '北區' }, { title: '北屯區', value: '北屯區' }, { title: '西屯區', value: '西屯區' }, { title: '南屯區', value: '南屯區' }, { title: '太平區', value: '太平區' }, { title: '大里區', value: '大里區' }, { title: '霧峰區', value: '霧峰區' }, { title: '烏日區', value: '烏日區' }, { title: '豐原區', value: '豐原區' }, { title: '后里區', value: '后里區' }, { title: '東勢區', value: '東勢區' }, { title: '石岡區', value: '石岡區' }, { title: '新社區', value: '新社區' }, { title: '和平區', value: '和平區' }, { title: '神岡區', value: '神岡區' }, { title: '潭子區', value: '潭子區' }, { title: '大雅區', value: '大雅區' }, { title: '大肚區', value: '大肚區' }, { title: '龍井區', value: '龍井區' }, { title: '沙鹿區', value: '沙鹿區' }, { title: '梧棲區', value: '梧棲區' }, { title: '清水區', value: '清水區' }, { title: '大甲區', value: '大甲區' }, { title: '外埔區', value: '外埔區' }, { title: '大安區', value: '大安區' }],
  彰化縣: [{ title: '彰化市', value: '彰化市' }, { title: '員林鎮', value: '員林鎮' }, { title: '和美鎮', value: '和美鎮' }, { title: '鹿港鎮', value: '鹿港鎮' }, { title: '溪湖鎮', value: '溪湖鎮' }, { title: '二林鎮', value: '二林鎮' }, { title: '田中鎮', value: '田中鎮' }, { title: '北斗鎮', value: '北斗鎮' }, { title: '花壇鄉', value: '花壇鄉' }, { title: '芬園鄉', value: '芬園鄉' }, { title: '大村鄉', value: '大村鄉' }, { title: '永靖鄉', value: '永靖鄉' }, { title: '伸港鄉', value: '伸港鄉' }, { title: '線西鄉', value: '線西鄉' }, { title: '福興鄉', value: '福興鄉' }, { title: '秀水鄉', value: '秀水鄉' }, { title: '埔心鄉', value: '埔心鄉' }, { title: '埔鹽鄉', value: '埔鹽鄉' }, { title: '大城鄉', value: '大城鄉' }, { title: '芳苑鄉', value: '芳苑鄉' }, { title: '竹塘鄉', value: '竹塘鄉' }, { title: '社頭鄉', value: '社頭鄉' }, { title: '二水鄉', value: '二水鄉' }, { title: '田尾鄉', value: '田尾鄉' }, { title: '埤頭鄉', value: '埤頭鄉' }, { title: '溪州鄉', value: '溪州鄉' }],
  南投縣: [{ title: '南投市', value: '南投市' }, { title: '埔里鎮', value: '埔里鎮' }, { title: '草屯鎮', value: '草屯鎮' }, { title: '竹山鎮', value: '竹山鎮' }, { title: '集集鎮', value: '集集鎮' }, { title: '名間鄉', value: '名間鄉' }, { title: '鹿谷鄉', value: '鹿谷鄉' }, { title: '中寮鄉', value: '中寮鄉' }, { title: '魚池鄉', value: '魚池鄉' }, { title: '國姓鄉', value: '國姓鄉' }, { title: '水里鄉', value: '水里鄉' }, { title: '信義鄉', value: '信義鄉' }, { title: '仁愛鄉', value: '仁愛鄉' }],
  雲林縣: [{ title: '斗六市', value: '斗六市' }, { title: '斗南鎮', value: '斗南鎮' }, { title: '虎尾鎮', value: '虎尾鎮' }, { title: '西螺鎮', value: '西螺鎮' }, { title: '土庫鎮', value: '土庫鎮' }, { title: '北港鎮', value: '北港鎮' }, { title: '莿桐鄉', value: '莿桐鄉' }, { title: '林內鄉', value: '林內鄉' }, { title: '古坑鄉', value: '古坑鄉' }, { title: '大埤鄉', value: '大埤鄉' }, { title: '崙背鄉', value: '崙背鄉' }, { title: '二崙鄉', value: '二崙鄉' }, { title: '麥寮鄉', value: '麥寮鄉' }, { title: '臺西鄉', value: '臺西鄉' }, { title: '東勢鄉', value: '東勢鄉' }, { title: '褒忠鄉', value: '褒忠鄉' }, { title: '四湖鄉', value: '四湖鄉' }, { title: '口湖鄉', value: '口湖鄉' }, { title: '水林鄉', value: '水林鄉' }, { title: '元長鄉', value: '元長鄉' }],
  嘉義市: [{ title: '東區', value: '東區' }, { title: '西區', value: '西區' }],
  嘉義縣: [{ title: '太保市', value: '太保市' }, { title: '朴子市', value: '朴子市' }, { title: '布袋鎮', value: '布袋鎮' }, { title: '大林鎮', value: '大林鎮' }, { title: '民雄鄉', value: '民雄鄉' }, { title: '溪口鄉', value: '溪口鄉' }, { title: '新港鄉', value: '新港鄉' }, { title: '六腳鄉', value: '六腳鄉' }, { title: '東石鄉', value: '東石鄉' }, { title: '義竹鄉', value: '義竹鄉' }, { title: '鹿草鄉', value: '鹿草鄉' }, { title: '水上鄉', value: '水上鄉' }, { title: '中埔鄉', value: '中埔鄉' }, { title: '竹崎鄉', value: '竹崎鄉' }, { title: '梅山鄉', value: '梅山鄉' }, { title: '番路鄉', value: '番路鄉' }, { title: '大埔鄉', value: '大埔鄉' }, { title: '阿里山鄉', value: '阿里山鄉' }],
  台南市: [{ title: '中西區', value: '中西區' }, { title: '東區', value: '東區' }, { title: '南區', value: '南區' }, { title: '北區', value: '北區' }, { title: '安平區', value: '安平區' }, { title: '安南區', value: '安南區' }, { title: '永康區', value: '永康區' }, { title: '歸仁區', value: '歸仁區' }, { title: '新化區', value: '新化區' }, { title: '左鎮區', value: '左鎮區' }, { title: '玉井區', value: '玉井區' }, { title: '楠西區', value: '楠西區' }, { title: '南化區', value: '南化區' }, { title: '仁德區', value: '仁德區' }, { title: '關廟區', value: '關廟區' }, { title: '龍崎區', value: '龍崎區' }, { title: '官田區', value: '官田區' }, { title: '麻豆區', value: '麻豆區' }, { title: '佳里區', value: '佳里區' }, { title: '西港區', value: '西港區' }, { title: '七股區', value: '七股區' }, { title: '將軍區', value: '將軍區' }, { title: '學甲區', value: '學甲區' }, { title: '北門區', value: '北門區' }, { title: '新營區', value: '新營區' }, { title: '後壁區', value: '後壁區' }, { title: '白河區', value: '白河區' }, { title: '東山區', value: '東山區' }, { title: '六甲區', value: '六甲區' }, { title: '下營區', value: '下營區' }, { title: '柳營區', value: '柳營區' }, { title: '鹽水區', value: '鹽水區' }, { title: '善化區', value: '善化區' }, { title: '大內區', value: '大內區' }, { title: '山上區', value: '山上區' }, { title: '新市區', value: '新市區' }, { title: '安定區', value: '安定區' }],
  高雄市: [{ title: '楠梓區', value: '楠梓區' }, { title: '左營區', value: '左營區' }, { title: '鼓山區', value: '鼓山區' }, { title: '三民區', value: '三民區' }, { title: '鹽埕區', value: '鹽埕區' }, { title: '前金區', value: '前金區' }, { title: '新興區', value: '新興區' }, { title: '苓雅區', value: '苓雅區' }, { title: '前鎮區', value: '前鎮區' }, { title: '小港區', value: '小港區' }, { title: '旗津區', value: '旗津區' }, { title: '鳳山區', value: '鳳山區' }, { title: '大寮區', value: '大寮區' }, { title: '鳥松區', value: '鳥松區' }, { title: '林園區', value: '林園區' }, { title: '仁武區', value: '仁武區' }, { title: '大樹區', value: '大樹區' }, { title: '大社區', value: '大社區' }, { title: '岡山區', value: '岡山區' }, { title: '路竹區', value: '路竹區' }, { title: '橋頭區', value: '橋頭區' }, { title: '梓官區', value: '梓官區' }, { title: '彌陀區', value: '彌陀區' }, { title: '永安區', value: '永安區' }, { title: '燕巢區', value: '燕巢區' }, { title: '田寮區', value: '田寮區' }, { title: '阿蓮區', value: '阿蓮區' }, { title: '茄萣區', value: '茄萣區' }, { title: '湖內區', value: '湖內區' }, { title: '旗山區', value: '旗山區' }, { title: '美濃區', value: '美濃區' }, { title: '內門區', value: '內門區' }, { title: '杉林區', value: '杉林區' }, { title: '甲仙區', value: '甲仙區' }, { title: '六龜區', value: '六龜區' }, { title: '茂林區', value: '茂林區' }, { title: '桃源區', value: '桃源區' }, { title: '那瑪夏區', value: '那瑪夏區' }],
  屏東縣: [{ title: '屏東市', value: '屏東市' }, { title: '潮州鎮', value: '潮州鎮' }, { title: '東港鎮', value: '恆春鎮' }, { title: '恆春鎮', value: '萬丹鄉' }, { title: '萬丹鄉', value: '長治鄉' }, { title: '長治鄉', value: '麟洛鄉' }, { title: '麟洛鄉', value: '九如鄉' }, { title: '九如鄉', value: '里港鄉' }, { title: '里港鄉', value: '鹽埔鄉' }, { title: '鹽埔鄉', value: '高樹鄉' }, { title: '高樹鄉', value: '萬巒鄉' }, { title: '萬巒鄉', value: '內埔鄉' }, { title: '內埔鄉', value: '竹田鄉' }, { title: '竹田鄉', value: '新埤鄉' }, { title: '新埤鄉', value: '枋寮鄉' }, { title: '枋寮鄉', value: '新園鄉' }, { title: '新園鄉', value: '崁頂鄉' }, { title: '崁頂鄉', value: '林邊鄉' }, { title: '林邊鄉', value: '南州鄉' }, { title: '南州鄉', value: '佳冬鄉' }, { title: '佳冬鄉', value: '琉球鄉' }, { title: '琉球鄉', value: '車城鄉' }, { title: '車城鄉', value: '滿州鄉' }, { title: '滿州鄉', value: '枋山鄉' }, { title: '枋山鄉', value: '霧台鄉' }, { title: '霧台鄉', value: '瑪家鄉' }, { title: '瑪家鄉', value: '泰武鄉' }, { title: '泰武鄉', value: '來義鄉' }, { title: '來義鄉', value: '春日鄉' }, { title: '春日鄉', value: '獅子鄉' }, { title: '獅子鄉', value: '牡丹鄉' }, { title: '牡丹鄉', value: '三地門鄉' }, { title: '三地門鄉', value: '' }],
  台東縣: [{ title: '臺東市', value: '臺東市' }, { title: '成功鎮', value: '成功鎮' }, { title: '關山鎮', value: '關山鎮' }, { title: '長濱鄉', value: '長濱鄉' }, { title: '海端鄉', value: '海端鄉' }, { title: '池上鄉', value: '池上鄉' }, { title: '東河鄉', value: '東河鄉' }, { title: '鹿野鄉', value: '鹿野鄉' }, { title: '延平鄉', value: '延平鄉' }, { title: '卑南鄉', value: '卑南鄉' }, { title: '金峰鄉', value: '金峰鄉' }, { title: '大武鄉', value: '大武鄉' }, { title: '達仁鄉', value: '達仁鄉' }, { title: '綠島鄉', value: '綠島鄉' }, { title: '蘭嶼鄉', value: '蘭嶼鄉' }, { title: '太麻里鄉', value: '太麻里鄉' }],
  花蓮縣: [{ title: '花蓮市', value: '花蓮市' }, { title: '鳳林鎮', value: '鳳林鎮' }, { title: '玉里鎮', value: '玉里鎮' }, { title: '新城鄉', value: '新城鄉' }, { title: '吉安鄉', value: '吉安鄉' }, { title: '壽豐鄉', value: '壽豐鄉' }, { title: '秀林鄉', value: '秀林鄉' }, { title: '光復鄉', value: '光復鄉' }, { title: '豐濱鄉', value: '豐濱鄉' }, { title: '瑞穗鄉', value: '瑞穗鄉' }, { title: '萬榮鄉', value: '萬榮鄉' }, { title: '富里鄉', value: '富里鄉' }, { title: '卓溪鄉', value: '卓溪鄉' }],
  宜蘭縣: [{ title: '宜蘭市', value: '宜蘭市' }, { title: '羅東鎮', value: '羅東鎮' }, { title: '蘇澳鎮', value: '蘇澳鎮' }, { title: '頭城鎮', value: '頭城鎮' }, { title: '礁溪鄉', value: '礁溪鄉' }, { title: '壯圍鄉', value: '壯圍鄉' }, { title: '員山鄉', value: '員山鄉' }, { title: '冬山鄉', value: '冬山鄉' }, { title: '五結鄉', value: '五結鄉' }, { title: '三星鄉', value: '三星鄉' }, { title: '大同鄉', value: '大同鄉' }, { title: '南澳鄉', value: '南澳鄉' }],
  澎湖縣: [{ title: '馬公市', value: '馬公市' }, { title: '湖西鄉', value: '湖西鄉' }, { title: '白沙鄉', value: '白沙鄉' }, { title: '西嶼鄉', value: '西嶼鄉' }, { title: '望安鄉', value: '望安鄉' }, { title: '七美鄉', value: '七美鄉' }],
  金門縣: [{ title: '金城鎮', value: '金城鎮' }, { title: '金湖鎮', value: '金湖鎮' }, { title: '金沙鎮', value: '金沙鎮' }, { title: '金寧鄉', value: '金寧鄉' }, { title: '烈嶼鄉', value: '烈嶼鄉' }, { title: '烏坵鄉', value: '烏坵鄉' }],
  連江縣: [{ title: '南竿鄉', value: '南竿鄉' }, { title: '北竿鄉', value: '北竿鄉' }, { title: '莒光鄉', value: '莒光鄉' }, { title: '東引鄉', value: '東引鄉' }],
};

export default YEAR_LIST;
